src/main/java/org/xabgesagtx/bm/events/persistence/model/Event.java
package org.xabgesagtx.bm.events.persistence.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.apache.commons.lang3.StringUtils;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown=true)
@Document
public class Event {

	@Id
	private String id;
	
    private LocalDate date;

    private LocalDateTime fullStartDate;

    private String title;
    
    private String description;
    
    private List<Band> bands;
    
    private Location location;
    
	private List<Link> links;
    
    private String price;
    
    private String moreInfos;
    
	private List<String> type;

    private boolean canceled;
    
    private boolean favorite;

	public String getLocationTitle() {
		return getLocation() != null ? getLocation().getTitle() : StringUtils.EMPTY;
	}
    
}

src/main/resources/templates/days.ftl
<#list days as day>
<b>${day}</b>

<#if eventsPerDay[day]?has_content>
<#list eventsPerDay[day] as event>
<#if event.canceled><b>Abgesagt</b> </#if><#if event.startTime?has_content>${event.startTime} </#if>${event.locationTitle}
<b>${event.title}</b> /e${event.cleanId}

</#list>
<#else>
Leider haben wir keine Veranstaltungen für diesen Termin.
</#if>
</#list>

src/main/resources/templates/event-details.ftl
${details.date}

<b>${details.title}</b> <#if details.canceled><b>(Abgesagt)</b></#if>
<#if details.startTime?has_content>${details.startTime} </#if>${details.locationTitle}
<#if details.price?has_content>
Preis: ${details.price}
</#if>
<#if details.description?has_content>

${details.description}
</#if>
<#if details.links?has_content>

<b>Links:</b>
<#list details.links as link>
<a href="${link.url}">${link.title}</a>
</#list>
</#if>
<#if details.bands?has_content>

<b>Bands:</b>
<#list details.bands as band>
${band.title} <#if band.description?has_content>- ${band.description}</#if>
<#list band.links as link><a href="${link.url}">${link.title}</a> </#list>
</#list>
</#if>